// <auto-generated />
using Cotizaciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Cotizaciones.Migrations
{
    [DbContext(typeof(CotizacionesContext))]
    [Migration("20180102180529_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Cotizaciones.Models.Cotizacion", b =>
                {
                    b.Property<int>("correlativoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripcion");

                    b.Property<string>("estado");

                    b.Property<string>("fecha");

                    b.Property<int>("montoTotal");

                    b.Property<string>("tipoServicio");

                    b.Property<int>("valorAgregado");

                    b.Property<int>("version");

                    b.HasKey("correlativoID");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("Cotizaciones.Models.CotizacionPersona", b =>
                {
                    b.Property<int>("CotizacionPersonaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("cotizacioncorrelativoID");

                    b.Property<int?>("personaId");

                    b.HasKey("CotizacionPersonaID");

                    b.HasIndex("cotizacioncorrelativoID");

                    b.HasIndex("personaId");

                    b.ToTable("CotizacionPersonas");
                });

            modelBuilder.Entity("Cotizaciones.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Materno");

                    b.Property<string>("Nombre");

                    b.Property<string>("Paterno");

                    b.Property<string>("Rut");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Cotizaciones.Models.CotizacionPersona", b =>
                {
                    b.HasOne("Cotizaciones.Models.Cotizacion", "cotizacion")
                        .WithMany()
                        .HasForeignKey("cotizacioncorrelativoID");

                    b.HasOne("Cotizaciones.Models.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaId");
                });
#pragma warning restore 612, 618
        }
    }
}
